import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to analytics test page!
          <Link href="/statistic">click to become just another statistic!</Link>
        </h1>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
